---@module 'documentation.bindings.usrcmds.churn'
--- `:DocMap churn [<rev-range>]` — churn × complexity, hottest first.
---
--- **Two things here cannot enter the artifact, for the same reason.** Git
--- history invalidates a committed map on the commit that embeds it; runtime
--- counts are personal, high-churn data that would do the same and mean
--- something different on every machine. A live command is where both belong,
--- which is why the runtime column costs nothing structurally: it is read at
--- the moment the list is built and written nowhere.
---
--- Not an Analysis panel, and it cannot become one: git data would make the
--- committed artifact invalidate itself on the very commit that embedded it,
--- since `--check` byte-compares. Same wall the History tab hit. So it lives
--- beside `impact` — live-computed into the quickfix list, nothing written.

local M = {}

---@param ctx Documentation.Bindings.Ctx
---@param arg string Everything after "churn" — a rev-range, or "" for all history.
function M.run(ctx, arg)
  local range = vim.trim(arg or "")
  local out_dir = ctx.cfg.out_dir or "docs/map"

  -- One record per commit: a record separator, then the paths it touched.
  -- `--no-merges` because a merge lists everything either side changed, which
  -- counts the same edit twice and rewards long-lived branches. Excluding the
  -- map is not cosmetic — in a repository that commits its own map it is
  -- regenerated by nearly every commit, so it would outrank everything real by
  -- an order of magnitude.
  local cmd = { "git", "log", "--no-merges", "--format=%x1e", "--name-only" }
  if range ~= "" then
    cmd[#cmd + 1] = range
  end
  vim.list_extend(cmd, { "--", ".", (":(exclude)%s"):format(out_dir) })

  -- `git log` over a repository's whole history is the slow part of this
  -- command, so it gets an indicator. It has to be `vim.system` + `vim.wait`
  -- rather than the `:wait()` this used before: `:wait()` does not drain
  -- scheduled callbacks, and a progress handle needs them to become visible at
  -- all — measured 0 visible samples under `:wait()` against 62 under
  -- `vim.wait`. See bindings/progress.lua. Same blocking behaviour either way,
  -- so nothing downstream changes.
  local progress = require("documentation.bindings.progress").create(
    ctx,
    range == "" and "reading history" or ("reading history (%s)"):format(range)
  )

  local proc
  vim.system(cmd, { cwd = ctx.cfg.root, text = true }, function(res)
    proc = res
  end)
  local settled = vim.wait(120000, function()
    return proc ~= nil
  end, 20)

  if not settled or not proc then
    if progress then
      progress:finish("git log timed out")
    end
    ctx.notify.warn("git log did not finish within 120s")
    return
  end

  if proc.code ~= 0 then
    if progress then
      progress:finish("git log failed")
    end
    ctx.notify.warn("git log failed: " .. vim.trim(proc.stderr or ""))
    return
  end

  local counts, seen_commits = {}, 0
  for record in (proc.stdout or ""):gmatch("[^\30]+") do
    local touched = {}
    for line in record:gmatch("[^\r\n]+") do
      local path = vim.trim(line)
      if path ~= "" then
        touched[path] = true
      end
    end
    if next(touched) then
      seen_commits = seen_commits + 1
      -- Per commit, not per occurrence: a path listed twice in one commit is
      -- still one change to it.
      for path in pairs(touched) do
        counts[path] = (counts[path] or 0) + 1
      end
    end
  end

  -- Closed here rather than at each `return` below: the tally above is pure
  -- string work over an in-memory buffer, and `churn.rank` is too, so the wait
  -- the indicator exists for is already over by this point.
  if progress then
    progress:finish(("%d commits examined"):format(seen_commits))
  end

  if seen_commits == 0 then
    ctx.notify.info(
      range == "" and ("No commits outside %s."):format(out_dir)
        or ("No commits in %s outside %s."):format(range, out_dir)
    )
    return
  end

  local churn = require("documentation.core.churn")
  local ir = ctx.handle.ir()

  -- The third axis, when this machine has one. Read here rather than inside
  -- `churn.rank`, which is pure and headless-testable and stays that way:
  -- it takes a plain `id -> counts` table and never learns that
  -- `runtime-analysis.nvim` exists.
  --
  -- Every step is allowed to fail into "no data": the plugin may not be
  -- installed, telemetry may never have been enabled for this namespace, or
  -- the tree may have no `opts.title` to derive a namespace from. None of
  -- those is an error and none of them changes the ranking -- they change
  -- whether a column is there.
  local join = require("documentation.core.telemetry_join")
  local namespace = join.namespace(ctx.cfg)
  local data = namespace and join.load(namespace)
  local calls = data and join.by_node(ir, data) or nil

  local result = churn.rank(counts, ir, seen_commits, calls)

  if #result.entries == 0 then
    ctx.notify.info(
      ("%d commit(s) examined, none touching a scanned module with documented functions."):format(
        seen_commits
      )
    )
    return
  end

  vim.fn.setqflist({}, " ", {
    title = ("docmap churn: %s"):format(range == "" and "all history" or range),
    items = churn.quickfix_items(result, ctx.cfg.root),
  })
  vim.cmd("copen")

  local top = result.entries[1]
  ctx.notify.info(
    ("%d module(s) over %d commits — hottest %s (%d × %d = %d)%s"):format(
      #result.entries,
      seen_commits,
      top.module or top.node,
      top.commits,
      top.complexity,
      top.score,
      result.unmatched > 0
          and (" · %d changed path(s) back no scanned module"):format(result.unmatched)
        or ""
    )
  )
end

return M
