---@module 'documentation.bindings.usrcmds.churn'
--- `:DocMap churn [<rev-range>]` — churn × complexity, hottest first.
---
--- Not an Analysis panel, and it cannot become one: git data would make the
--- committed artifact invalidate itself on the very commit that embedded it,
--- since `--check` byte-compares. Same wall the History tab hit. So it lives
--- beside `impact` — live-computed into the quickfix list, nothing written.

local M = {}

---@param ctx Documentation.Bindings.Ctx
---@param arg string Everything after "churn" — a rev-range, or "" for all history.
function M.run(ctx, arg)
  local range = vim.trim(arg or "")
  local out_dir = ctx.cfg.out_dir or "docs/map"

  -- One record per commit: a record separator, then the paths it touched.
  -- `--no-merges` because a merge lists everything either side changed, which
  -- counts the same edit twice and rewards long-lived branches. Excluding the
  -- map is not cosmetic — in a repository that commits its own map it is
  -- regenerated by nearly every commit, so it would outrank everything real by
  -- an order of magnitude.
  local cmd = { "git", "log", "--no-merges", "--format=%x1e", "--name-only" }
  if range ~= "" then
    cmd[#cmd + 1] = range
  end
  vim.list_extend(cmd, { "--", ".", (":(exclude)%s"):format(out_dir) })

  local proc = vim.system(cmd, { cwd = ctx.cfg.root, text = true }):wait()
  if proc.code ~= 0 then
    ctx.notify.warn("git log failed: " .. vim.trim(proc.stderr or ""))
    return
  end

  local counts, seen_commits = {}, 0
  for record in (proc.stdout or ""):gmatch("[^\30]+") do
    local touched = {}
    for line in record:gmatch("[^\r\n]+") do
      local path = vim.trim(line)
      if path ~= "" then
        touched[path] = true
      end
    end
    if next(touched) then
      seen_commits = seen_commits + 1
      -- Per commit, not per occurrence: a path listed twice in one commit is
      -- still one change to it.
      for path in pairs(touched) do
        counts[path] = (counts[path] or 0) + 1
      end
    end
  end

  if seen_commits == 0 then
    ctx.notify.info(
      range == "" and ("No commits outside %s."):format(out_dir)
        or ("No commits in %s outside %s."):format(range, out_dir)
    )
    return
  end

  local churn = require("documentation.core.churn")
  local result = churn.rank(counts, ctx.handle.ir(), seen_commits)

  if #result.entries == 0 then
    ctx.notify.info(
      ("%d commit(s) examined, none touching a scanned module with documented functions."):format(
        seen_commits
      )
    )
    return
  end

  vim.fn.setqflist({}, " ", {
    title = ("docmap churn: %s"):format(range == "" and "all history" or range),
    items = churn.quickfix_items(result, ctx.cfg.root),
  })
  vim.cmd("copen")

  local top = result.entries[1]
  ctx.notify.info(
    ("%d module(s) over %d commits — hottest %s (%d × %d = %d)%s"):format(
      #result.entries,
      seen_commits,
      top.module or top.node,
      top.commits,
      top.complexity,
      top.score,
      result.unmatched > 0
          and (" · %d changed path(s) back no scanned module"):format(result.unmatched)
        or ""
    )
  )
end

return M
