---@meta
---@module 'documentation.@types'

---Configuration for a docmap run. Every field that could hardcode a
---particular repo's layout is an option, so other plugins can point docmap at
---their own tree.
---@class Documentation.Opts
---@field root string Absolute path to the repository root. Omitted in a `usrcmds.setup()` call, `:DocMap`/`:DocBrowse` resolve it **per invocation** from the current buffer's file (see `root_markers`); set it to pin every invocation to one tree, which is what a consuming plugin generating its own map wants.
---@field root_markers? string[] `usrcmds.setup()` only, and only when `root` is absent: marker names `vim.fs.root` walks up for to find the repository containing the current buffer's file. Default `{ ".git" }` — matches a worktree's `.git` *file* as well as a normal `.git` directory. Falls back to the working directory for a buffer with no file behind it.
---@field source? string Directory to scan, relative to `root`. Default "lua".
---@field lua_root? string Directory the Lua module path is relative to. Default "lua".
---@field title? string Display name for the root node. Default: the source directory name.
---@field types_dir? string Directory name holding type definitions, treated as a module attribute. Default "@types".
---@field out_dir? string Output directory, relative to `root`. Default "docs/map".
---@field repo_url? string Base URL used to build source links (e.g. "https://github.com/user/repo").
---@field branch? string Branch used in source links. Default "main".
---@field extra_checks? Documentation.Check[] Repo-specific drift checks appended to the generic ones.
---@field calls_heuristic? boolean Also emit call edges whose target was guessed by unique-name match rather than resolved through a require alias. Off by default — a wrong call graph is worse than an incomplete one. Default false.
---@field docs_heuristic? boolean Also resolve documentation references written as a bare, tree-unique function name rather than a qualified one. Off by default, same posture as `calls_heuristic` and for the same reason — measured on this repository, the bare names doing the matching were `write`/`open`/`scan`/`add`/`esc`, all file-local helpers and all ordinary English words. Default false.
---@field dead_code? boolean Also report *published* functions with no caller in the tree as dead-code candidates. Off by default, and that is not timidity: a library consists of functions with no internal caller by design, so this reports much of the public API on any tree that is a library. The always-on half of the check — file-local and `@internal` functions — needs no flag because there the statement holds. Default false.
---@field layers? Documentation.LayerRule[] Module-prefix layering rules for the `layer-violation` check. Empty/absent disables the check.
---@field luals? boolean Merge `lua-language-server --doc` output into the IR (class/alias/field detail, type-reference edges). Off by default — a full-tree run costs real seconds. Default false.
---@field luals_timeout_ms? integer Kill the `lua-language-server --doc` run after this long. Default 60000.
---@field progress_style? "auto"|"notify"|"statusline"|"fidget"|"float"|"kit" Indicator while a long `:DocMap` runs (`full`'s LuaLS pass, `churn`'s history walk). Read by the bindings layer only — `core` stays UI-free. Needs lib.nvim, no-op without it. Default "auto".
---@field command_name? string Passed to `docmap.command.setup`: register a user command under this name. Default "DocMap".
---@field browse_command_name? string Passed to `docmap.command.setup`: register the editor-side map browser under this name. Default "DocBrowse".
---@field keys? table<Documentation.Browse.KeyAction, string|string[]|false> Rebind or disable `:DocBrowse`'s keys, by action name. `false` turns an action off; a string or list replaces its left-hand sides; unlisted actions keep their defaults. Every binding is buffer-local to the browser, so a replacement only has to be free inside it. See `Documentation.Browse.KeyAction` for the list.
---@field which_key? boolean Register `:DocBrowse`'s bindings with which-key when it is installed. Default true, and a no-op without which-key — the registration is guarded by `pcall`. Set false to keep the browser out of the which-key popup.
---@field debug? boolean Collect per-stage scan timings and report them after a `:DocMap`. Off by default. Coarse on purpose — one entry per pipeline stage, answering "which stage is slow"; anything finer is a profiler's job. Costs nothing when off: `timing.measure` is a direct call with no clock read.
---@field watch? boolean `install()` only: rescan on `BufWritePost` under `source/**.lua`, debounced. Default false.
---@field watch_ms? integer `install()` only: debounce interval for `watch`. Default 500.
---@field tag_files? table<string, string> Doxygen `TAGFILES` equivalent: module-prefix -> another project's `docs/map`-shaped directory (must contain a committed `module_map.json`). A `requires_external` module matching the prefix resolves against that project's own artifact instead of staying an inert box. Local paths only — read synchronously during `scan_full()`, same as `opts.root` itself, so `--check` stays deterministic and offline. See `tagfiles.lua`.
---@field tests_dir? string Directory (relative to `root`) scanned for auto-derived test coverage — see `coverage.lua`. Default "TESTS". A missing directory is not an error: every function is simply left `tested = false`.
---@field quicks? Documentation.Quicks.Opts Tuning for the Quicks verdicts — thresholds and how many of each polarity to keep. Absent means the defaults in `core/quicks.lua`.
---@field badge? boolean Write `coverage.svg` (a shields.io-shaped doc-coverage badge, see `doccoverage.lua`/`render/badge.lua`) alongside the other artifacts. Off by default — most consumers of `generate()` do not want an extra committed file they never asked for. Default false.
---@field pdf? boolean Also write `overview.pdf` (same content as `overview.md`) via pdfport.nvim (github.com/StefanBartl/pdfport.nvim, optional dependency, soft-required — needs pandoc + a PDF engine). Off by default. Unlike the other artifacts this is asynchronous, so it is reported separately from `:DocMap`'s "wrote N artifacts" notification, not folded into it. See `documentation.write_pdf_artifact`. Default false.
---@field telemetry_namespace? string The `runtime-analysis.telemetry` namespace to join against for the `telemetry` browse mode and dead-function suppression (ECOSYSTEM.md step 8). Default `title` — every telemetry instance in this ecosystem is namespaced by the plugin's own display name, so a caller who already sets `title` needs nothing extra; set this only when the two genuinely differ.
---@field telemetry? boolean Self-instrument this tree's own `require("documentation")` aggregate with `runtime-analysis.telemetry`, writing to `telemetry_namespace`/`title` — the write side of the `telemetry` browse mode above. Default true, and a no-op without runtime-analysis.nvim installed — same opt-out shape as `which_key`. Set false to keep this plugin out of its own telemetry data entirely. See `documentation.core.telemetry_self`.

---A repo-specific drift check.
---@alias Documentation.Check fun(ir: Documentation.IR, opts: Documentation.Opts): Documentation.Finding[]

---A source file's leading doc-comment block, parsed. What `scan.lua`'s
---`parse_header` has always returned; named here so `Documentation.
---LangBackend`'s `parse_header` field can point at one shape shared by every
---language's implementation of it, not a shape only Lua's happens to match.
---@class Documentation.Header
---@field module string? The declared module path, however this language spells that — `---@module` for Lua, a JSDoc `@module` tag for JS/TS.
---@field summary string
---@field body string
---@field tags table<string, string>

---One supported source language, selected by file extension. See
---`core/lang_registry.lua` for why this exists as a registry rather than an
---if/elseif chain in `scan.lua`, and `docs/ROADMAP/MULTILANG.md` for what
---adding a second one (beyond the Lua reference registration in
---`core/lang/lua.lua`) actually costs.
---@class Documentation.LangBackend
---@field name string Short identifier, e.g. `"lua"` — the same string it registers itself under, kept on the table too so `lang_registry.reset()` can re-register an already-cached backend by name without needing to re-require (and thus re-execute) its module.
---@field module_file string? Filename that marks a directory as owning a module of its own (Lua: `"init.lua"`). `nil` for a language with no such convention, where every source file is its own node.
---@field is_source fun(filename: string): boolean Whether `filename` (bare, no path) is a source file this backend scans.
---@field module_tag boolean? Whether this language has a `@module`-tag-shaped authoring convention worth `check.lua`'s `missing-module-tag` checking the absence of. Lua: `true` (its canonical module name cannot be recovered from the file path alone). A language whose module identity already is its file path (JS/TS's ESM imports resolve by path): `false` — nothing tag-shaped can be "missing." Absent/`nil` is treated as `true`, the conservative default that preserves today's behavior for a backend that never states an opinion.
---@field parse_header fun(path: string): Documentation.Header
---@field scan_file fun(path: string): Documentation.FunctionInfo[], Documentation.RawCall[], Documentation.RawRequire[], Documentation.SymbolInfo[], table[], Documentation.EndpointSpec[], integer Same seven-value shape `functions.lua`'s `scan_file` already returns. The fifth (`plugins`) and sixth (`endpoints`) are ecosystem-specific — see `docs/FRAMEWORK_CONVENTIONS.md`/`docs/ECOSYSTEM.md` on why each is a layer *above* language support, not part of this contract — and a backend with no equivalent convention returns `{}` there, not `nil`.

---One layering rule: modules whose `@module` starts with `from` may not
---require modules whose `@module` starts with `to`. Both are plain prefixes,
---not patterns — `lib.vim` matches `lib.vim.buffer` but never `lib.vimx`.
---@class Documentation.LayerRule
---@field from string Module prefix of the requiring side.
---@field to string Module prefix that side must not reach into.
---@field why string? Appended to the finding message.

---@alias Documentation.Severity "error"|"warn"|"info"

---@alias Documentation.Kind
---| "module"    # A directory containing init.lua
---| "namespace" # A directory without init.lua, grouping others
---| "file"      # A non-init.lua Lua file

---One node of the map.
---@class Documentation.Node
---@field id string Stable identifier — the repo-relative path.
---@field kind Documentation.Kind
---@field name string Display name (directory or file name).
---@field path string Repo-relative path to the directory or file.
---@field source string? Repo-relative path to the Lua source backing this node.
---@field module string? The declared `---@module` path.
---@field summary string One-sentence description, from the header block.
---@field body string Remaining header prose.
---@field readme string? Repo-relative path to a sibling README.md.
---@field types string[] Repo-relative paths of the module's type files.
---@field export ("function"|"table"|"other"|"none")? Export shape of the source file.
---@field parent string? Parent node id.
---@field depth integer Distance from the root node.
---@field children string[] Child node ids, directories first, then files.
---@field types_detail Documentation.TypeInfo[]? `@class`/`@alias` detail for this node's `types` files, from `lua-language-server --doc`. `nil` when LuaLS enrichment did not run; `{}` is a real "ran, found nothing here" result.
---@field functions Documentation.FunctionInfo[] Documented functions found in this node's own source file (not its `@types/` files). Always an array, never nil — unlike `types_detail`, this runs unconditionally as part of `scan()`, no LuaLS required.
---@field plugins Documentation.PluginSpec[] Plugin-manager (lazy.nvim-shaped) spec entries found in this node's own source — see `core/plugins.lua`. Always an array, empty for a source file that is not a plugin-spec file, which is nearly all of them; runs unconditionally as part of `scan()`, no configuration required.
---@field endpoints Documentation.EndpointSpec[] Call-based route registrations (Express/Fastify/Koa-shaped) found in this node's own source — see `core/endpoints.lua`. Always an array, empty for a source file with no route registrations (nearly all of them, and every non-JS/TS file); runs unconditionally as part of `scan()`.
---@field requires string[] Node ids this node requires, sorted. Derived from `ir.edges`; an index for convenience, not a second source of truth.
---@field required_by string[] Node ids that require this node, sorted. Same derivation.
---@field requires_external string[] Module paths this node requires that resolve to nothing in the scanned tree — other plugins, or anything outside `source`. Plain strings, not invented nodes: the map only claims to describe what it scanned. The Deps view can draw them on request.
---@field requires_raw Documentation.RawRequire[] Unresolved `require` occurrences. Internal to the scan pipeline (`deps`/`calls` consume it); deliberately not serialized into `module_map.json`.
---@field calls_raw Documentation.RawCall[] Unresolved call sites. Internal, same as `requires_raw`.
---@field symbols Documentation.SymbolInfo[] Module-scope tables, constants and bindings in this node's own source. Always an array; runs unconditionally as part of `scan()`.
---@field stats Documentation.Stats Counts over this node and everything below it.

---A single `@class`/`@alias` parsed from `lua-language-server --doc` output,
---attached to whichever node owns the file it's defined in.
---@class Documentation.TypeInfo
---@field name string Fully-qualified type name, e.g. "Documentation.Node".
---@field kind "class"|"alias"
---@field desc string
---@field file string Repo-relative file the type is defined in.
---@field fields Documentation.TypeField[] Empty for aliases and field-less classes.
---@field extends string[] Parent class names as written in `---@class Child : A, B`, in source order. Always an array (empty when the class has no parent, and for every alias). Names are kept even when the parent is not declared anywhere in the tree — those simply produce no `"extends"` edge, the same way `requires_external` keeps a require whose target lives outside the map.

---@class Documentation.TypeField
---@field name string
---@field view string Raw LuaCATS type text, e.g. "table<string, Documentation.Node>".
---@field desc string

---One `---@param` on a documented function.
---@class Documentation.ParamInfo
---@field name string
---@field type string Raw LuaCATS type text.
---@field optional boolean Declared as `name?`.
---@field desc string

---One `---@return` on a documented function. LuaLS allows a bare type with no
---name (`---@return boolean`); `name` is nil in that case.
---@class Documentation.ReturnInfo
---@field type string Raw LuaCATS type text.
---@field name string?
---@field desc string

---One `---@overload` on a documented function: an additional way the same
---function may be called, expressed as a LuaCATS `fun(...)` type literal
---rather than a second function definition — Lua has no true overloading,
---so `@overload` documents alternative call shapes of the *one* function
---below it, not alternative implementations.
---@class Documentation.OverloadInfo
---@field raw string The `@overload` value exactly as written, e.g. `fun(x: string): boolean`. Always present, even when `params`/`returns` below are empty because the value did not parse as `fun(...)`.
---@field params Documentation.ParamInfo[] Parsed from inside the parens. `desc` is always `""` — a `fun()` type literal carries no per-parameter prose, only `name: type`. `optional` and `name` behave as they do on `Documentation.ParamInfo`.
---@field returns Documentation.ReturnInfo[] Parsed from after the parens. `name`/`desc` are always nil/`""` for the same reason as `params`.

---A single documented function, extracted via `documentation.core.functions`
---(a `vim.treesitter` query, not `lua-language-server --doc` — see that
---module's header for why). Attached to whichever node owns the file it's
---defined in.
---@class Documentation.FunctionInfo
---@field name string Qualified name as written, e.g. "M.scan_full" or "M.bar".
---@field signature string Name + parameter list, e.g. "scan_full(opts)".
---@field summary string One-line prose from the doc block, if any.
---@field line integer 1-based line the function definition starts on.
---@field line_end integer 1-based line the function definition ends on (the `end` keyword). With `line`, the span `docmap.history` maps a diff hunk's changed lines onto.
---@field params Documentation.ParamInfo[]
---@field returns Documentation.ReturnInfo[]
---@field generic string[] `@generic` type names, if any.
---@field deprecated string? `@deprecated` text; nil when not deprecated.
---@field async boolean
---@field nodiscard boolean
---@field local_refs integer How often this function's bare name is mentioned elsewhere in its own file. Answers the one question call edges cannot: a function passed as a *value* (`vim.system(cmd, on_exit)`) is used but never appears at a call site. Deliberately coarse — an unrelated `x.read` counts toward a local `read` — because over-counting errs toward "used", which is the safe direction.
---@field complexity integer Cyclomatic complexity (McCabe): 1 + one per `if`/`elseif`/`while`/`for`/`repeat`/`and`/`or`, counted over the function's own subtree including nested anonymous closures. Always computed, unconditionally — unlike `tested`/`documented`, there is no later resolve step that could derive it from the IR alone.
---@field shape string Structural fingerprint: a hash of the treesitter node *types* over this function's whole subtree, never their text — so two functions differing only in identifier and literal names share one. What `duplicates.lua` groups by. Computed during the scan for the same reason as `complexity`: only there does the parse tree exist.
---@field shape_size integer Node count behind `shape`. The duplicate detector's size floor applies to this: below it a shared shape means nothing, because every tree has a dozen one-line accessors that match each other.
---@field internal boolean Declared `---@internal`: part of the implementation, not of the module's published surface. Sharpens every question of the form "is this used" — `undocumented-param` skips it, the diff counts it as a helper, and a dead-function report can trust it.
---@field tested boolean Set by `coverage.resolve` (R2): this function's bare name is mentioned somewhere under `opts.tests_dir`. `false` until `coverage.resolve` has run, and even then means "not found by name in a spec" rather than "definitely untested" — see that module's header for the blind spot.
---@field documented boolean Set by `doccoverage.resolve` (R4): a non-empty summary plus fully, correctly documented parameters. `false` for `@internal` functions regardless — an internal function's documentation bar is the author's own, and folding it into a "published API" number would answer a question nobody asked.
---@field see string[] Raw `@see` targets, unresolved — `docmap.check` validates them.
---@field overload Documentation.OverloadInfo[] Additional call signatures, each parsed the same way the function's own `params`/`returns` are — see `Documentation.OverloadInfo`.
---@field todo string[] `@todo` entries, one per occurrence. Collected into the Notes tab's aggregate list, the way Doxygen's `\todo` feeds its Todo List.
---@field bug string[] `@bug` entries, one per occurrence.
---@field test string[] `@test` entries, one per occurrence.
---@field example string? `@example` block text, if any.
---@field since string? `@since` text, if any.
---@field is_hook boolean? True when this function's name matches React's own hook convention (`^use[A-Z]`, the same signal `eslint-plugin-react-hooks` relies on) — set by `core/lang/ecma.lua`, `nil` for languages with no such convention (Lua never sets it).
---@field snippet string? This function's own source, bounded to `core/snippet.lua`'s `MAX_LINES` — the embeddable tier of `docs/ECOSYSTEM.md` §3.5's hover preview. `nil` for an empty/invalid span, a real absence rather than an empty string standing in for one.
---@field snippet_omitted integer Lines cut off past the cap; `0` when the whole function fit.

---What kind of relationship an edge in `ir.edges` records. One array with a
---discriminator rather than three parallel arrays, so layout, filtering and
---drawing exist once each instead of once per relationship.
---@alias Documentation.EdgeKind
---| "type"    # A `---@field` on one class names another class.
---| "extends" # One class inherits from another (`---@class Child : Parent`).
---| "require" # One file calls `require` on another module in the tree.
---| "call"    # One function calls another.

---What a module-scope binding turned out to be. Deliberately coarse: the
---distinction that matters when reading a module is "lookup table" vs "tuned
---number" vs "something computed at load time", not a type.
---@alias Documentation.SymbolKind
---| "table"    # Bound to a table constructor.
---| "constant" # Bound to a literal number, string or boolean.
---| "binding"  # Anything else evaluated at load time.

---One module-scope table, constant or binding, from `documentation.core.symbols`.
---Functions and `require` bindings are excluded — `docmap.functions` and
---`docmap.deps` own those.
---@class Documentation.SymbolInfo
---@field name string As written, e.g. "CACHE" or "M.defaults".
---@field kind Documentation.SymbolKind
---@field detail string Short right-hand-side summary: "12 fields" for a table, the literal for a constant, a condensed expression otherwise.
---@field summary string One-line prose from the doc block above it, if any.
---@field line integer 1-based line the binding starts on.

---One plugin-manager spec entry — currently lazy.nvim's shape only, see
---`core/plugins.lua`'s header for why packer/vim-plug are a separate,
---unbuilt extractor rather than a bent version of this one.
---@class Documentation.PluginSpec
---@field repo string The "author/repo" shorthand, or the `name`/`dir`/`url` fallback when no positional string is given.
---@field line integer 1-based line the spec entry starts on.
---@field lazy boolean? Explicit `lazy = true|false`; `nil` when unstated — lazy.nvim's own default is true when any trigger field is present, false otherwise, which this does not attempt to re-derive.
---@field event string[] `event` trigger(s), normalised to an array whether declared as one string or several.
---@field cmd string[] `cmd` trigger(s), same normalisation.
---@field ft string[] `ft` trigger(s), same normalisation.
---@field keys string[] Left-hand sides of `keys` trigger entries — what the mapping does is not collected, only when it makes the plugin load.
---@field dependencies string[] Dependency repo shorthands, one level of nested-spec-table unwrapped.
---@field enabled boolean? Explicit `enabled = true|false`; `nil` when absent or set to a function (dynamic — not evaluated).
---@field priority integer?
---@field branch string?
---@field version string?
---@field dir string?
---@field url string?
---@field has_opts boolean Whether the spec sets `opts` at all, not what it contains.
---@field has_config boolean Whether the spec sets `config` (a table, `true`, or a function) at all.

---One call-based route registration — `app.get("/path", handler)`-shaped,
---see `core/endpoints.lua`'s header for exactly what is and is not
---recognized, and why file-based routing (Next.js/SvelteKit/Nuxt/Remix) is
---a separate, unbuilt concept rather than a bent version of this one.
---@class Documentation.EndpointSpec
---@field method string HTTP method, lowercase, as written (`"get"`, `"post"`, ... or `"all"`).
---@field path string Route path as written, including any Express-style params (`":id"`).
---@field handler string? The handler's declared name, when it is a named reference; `nil` for an inline function/arrow expression with nothing to name.
---@field line integer 1-based line the route registration call sits on.
---@field framework string? Recognized from this file's own imports (`express`/`fastify`/`koa`/`connect`/`restify`/`hapi`); `nil` when the call shape matched but no known routing package was imported in this file.
---@field documented boolean Whether the handler (when named) is one of this file's own functions with a non-empty summary; `false` for an inline handler or an unresolved name.

---Counts over a node and everything below it. Aggregated rather than own-only:
---the question a directory answers is "how big is this part of the tree".
---@class Documentation.Stats
---@field modules integer Directories with an `init.lua`.
---@field namespaces integer Directories without one.
---@field files_lua integer `.lua` files, including `init.lua` and `@types/`.
---@field files_md integer Markdown files, including READMEs.
---@field files_other integer Everything else that is not a directory.
---@field lines integer Lines of Lua.
---@field functions integer Documented top-level functions.
---@field symbols integer Module-scope tables, constants and bindings.
---@field types integer `@class`/`@alias` definitions — only non-zero once LuaLS enrichment ran.

---A directed edge between two nodes. Which of the optional fields are set is
---determined by `kind` — see each field. `ir.edges` is always an array, empty
---when nothing produced edges, so renderers never need a presence check.
---@class Documentation.Edge
---@field kind Documentation.EdgeKind
---@field from string Node id of the referencing/requiring/calling side.
---@field to string Node id of the referenced/required/called side.
---@field from_class string? `kind="type"|"extends"`: fully-qualified name of the referencing/inheriting class.
---@field to_class string? `kind="type"|"extends"`: fully-qualified name of the referenced/inherited class.
---@field via string? `kind="type"`: field name that carries the reference. Absent for `"extends"`, where nothing mediates the relationship.
---@field to_module string? `kind="require"`: the module path as written in the `require` call.
---@field deferred boolean? `kind="require"`: every occurrence sits inside a function body, so this is a lazy load rather than a load-time dependency. Absent means at least one load-time require.
---@field from_fn string? `kind="call"`: declared name of the calling function, e.g. "M.generate".
---@field to_fn string? `kind="call"`: declared name of the called function.
---@field line integer? `kind="require"|"call"`: 1-based line of the call site.
---@field confidence Documentation.Confidence? `kind="call"`: how the target was determined.

---How a call edge's target was determined. `"exact"` means the callee was
---resolved through a `require` alias, the module's own export table, or a
---file-local function — a syntactic fact. `"heuristic"` means the name matched
---exactly one function in the whole tree and nothing else pinned it down; only
---produced when `opts.calls_heuristic` is set, and drawn differently.
---@alias Documentation.Confidence "exact"|"heuristic"

---One `require(...)` occurrence as found in a source file, before it is
---resolved against the map. `alias` is set for the `local x = require("y")`
---form, which is what makes call resolution possible at all.
---@class Documentation.RawRequire
---@field module string The module path as written.
---@field alias string? Local name it was bound to, if any.
---@field member string? Trailing field access, as in `local x = require("y").z`.
---@field deferred boolean? The call sits inside a function body — a lazy load, not a load-time dependency.
---@field line integer

---One call site as found in a source file, before it is resolved against the
---map. `callee` is the raw text of the called expression (`fs.read`, `M.foo`,
---`helper`), `from_fn` the declared name of the top-level function it sits in.
---@class Documentation.RawCall
---@field callee string
---@field from_fn string?
---@field line integer

---One added or removed require edge in a `Documentation.Diff`.
---@class Documentation.DiffEdge
---@field edge string `"<from id> -> <to id>"`.
---@field deferred boolean? The edge is a lazy require.
---@field changed boolean? The edge existed before but stopped being lazy — a load-time dependency that did not exist previously, which is how initialisation cycles get introduced.

---What one revision changed about the *shape* of the tree, from
---`documentation.core.diff`.
---@class Documentation.Diff
---@field nodes_added string[] Node ids, sorted.
---@field nodes_removed string[]
---@field functions_added string[] `"<node id>#<declared name>"`, sorted.
---@field functions_removed string[]
---@field deps_added Documentation.DiffEdge[]
---@field deps_removed Documentation.DiffEdge[]
---@field deps_comparable boolean False when the older map predates the dependency graph, in which case the dependency, cycle and impact sections are empty because they are unknowable, not because nothing changed.
---@field cycles_added string[] Load-time cycles introduced.
---@field cycles_removed string[]
---@field impact_changed { id: string, before: integer, after: integer }[] Sorted by how much the blast radius moved.

---A drift finding.
---@class Documentation.Finding
---@field severity Documentation.Severity
---@field check string Stable check identifier, e.g. "missing-summary".
---@field node string? Node id the finding attaches to.
---@field message string Human-readable description.

---Metadata about a scan. Deliberately carries no timestamp: a generated-at
---field would make every regeneration a diff even when nothing changed, which
---defeats `--check`.
---@class Documentation.Meta
---@field title string
---@field source string
---@field types_dir string
---@field repo_url string?
---@field branch string
---@field schema integer IR schema version.
---@field counts table<string, integer> Node counts per kind.

---A `requires_external` module resolved against another project's own
---committed docmap artifact (`opts.tag_files`) — Doxygen `TAGFILES`
---equivalent. `html` is a path to that project's generated page with a bare
---`#<node id>` fragment, the same shorthand a hand-typed or shared link uses.
---@class Documentation.TagLink
---@field title string The resolved node's `module` (or `name` if declared none).
---@field html string Path to the external project's `index.html`, with a `#<node id>` fragment.

---One file's changed line ranges, parsed out of `git diff --unified=0` by
---`docmap.history`. `old_path`/`new_path` are nil on the `/dev/null` side of
---an added or deleted file, and differ from each other on a rename.
---@class Documentation.History.FileDiff
---@field old_path string? Path in the parent revision.
---@field new_path string? Path in the revision itself.
---@field old { first: integer, last: integer }[] Changed line ranges, parent side.
---@field new { first: integer, last: integer }[] Changed line ranges, this side.

---A function a diff's changed lines fall inside.
---@class Documentation.History.Touched
---@field node string Node id owning the function.
---@field fn string Declared function name.
---@field line integer 1-based line the function starts on.
---@field signature string

---One call site targeting a touched function.
---@class Documentation.History.Caller
---@field node string Node id the call is written in.
---@field fn string Declared name of the calling function.
---@field line integer? 1-based line of the call site.

---What one diff radiates to — see `docmap.history`.
---@class Documentation.History.Impact
---@field files string[] Every changed path the diff named, sorted.
---@field touched Documentation.History.Touched[] Functions whose span the changed lines fall inside.
---@field callers table<string, Documentation.History.Caller[]> Keyed `"<node>#<fn>"`: direct callers of each touched function.
---@field calling_modules string[] Distinct nodes containing at least one of those call sites — the precise answer.
---@field impacted_modules string[] Transitive `required_by` closure of the touched nodes (`deps.impact`) — the coarser answer.
---@field unattributed string[] Changed paths that produced no function attribution: not a scanned node, an IR without functions, or lines outside every function.
---@field approximate boolean True when at least one attribution came from an artifact without `line_end`, so function spans had to be approximated from the next function's start. Over-attributes rather than under-attributes; a UI should say so.

---The intermediate representation every renderer and check reads.
--- One entry in the name -> entity index `docs.lua` resolves mentions
--- against. `fn` is set only for `kind = "function"`.
---@class Documentation.Docs.Entity
---@field kind "module"|"function"
---@field node string Node id.
---@field fn string? Declared function name, e.g. "M.scan_full".

--- A resolved mention: an entity plus how confidently it was placed. Same
--- vocabulary as `Documentation.Confidence` on a call edge, for the same
--- reason — `"heuristic"` here means a bare name that exactly one module in
--- the tree owns, and nothing else pinned it down.
---@class Documentation.Docs.Target : Documentation.Docs.Entity
---@field confidence Documentation.Confidence

--- Built once per scan by `docs.build_index`. `bare` deliberately holds only
--- names owned by exactly one function in the whole tree; a name owned twice
--- is removed rather than resolved to a winner.
---@class Documentation.Docs.Index
---@field exact table<string, Documentation.Docs.Entity> Module paths, declared function names, and qualified `module.bare` forms.
---@field bare table<string, Documentation.Docs.Entity> Unqualified function names that are unique tree-wide.
---@field modules table<string, string> Module path -> node id.
---@field fns_by_module table<string, table<string, string>> Module path -> bare name -> declared name.

--- One documentation file in the corpus.
---@class Documentation.Docs.File
---@field path string Repo-relative.
---@field title string First `#` heading, or the filename when there is none.
---@field refs integer Mentions in this file that resolved to something.

--- One place a doc mentions an entity.
---@class Documentation.Docs.Ref
---@field doc string Repo-relative path of the mentioning file.
---@field line integer 1-based line of the mention.
---@field text string The code span exactly as written.
---@field context string The surrounding line, whitespace-collapsed and length-bounded.
---@field confidence Documentation.Confidence

--- A code span whose longest dotted prefix is a real module but whose
--- remainder names nothing in it — prose describing a function that has been
--- renamed or removed. See `docs.lua`'s header for why the rule is this
--- narrow.
---@class Documentation.Docs.Missing
---@field doc string
---@field line integer
---@field text string The span as written.
---@field module string The module path that did resolve.
---@field node string? Node id of that module, so a finding can be attributed without rebuilding the index.
---@field missing string The remainder that did not.

--- `ir.docs`. Keys of `refs` are node ids for modules and `nodeId#fnName`
--- for functions — the same key shape `calls.lua` and the rendered page
--- already use.
---@class Documentation.Docs.Result
---@field files Documentation.Docs.File[] Sorted by path.
---@field refs table<string, Documentation.Docs.Ref[]> Each list sorted by doc then line, capped, with a `more` count when it overflowed.
---@field missing Documentation.Docs.Missing[] Sorted by doc, line, text.

---One verdict about the tree — see `core/quicks.lua`.
---@class Documentation.Quick
---@field id string Stable identifier, e.g. "test-coverage". What a threshold override is keyed by (underscores for hyphens).
---@field polarity "good"|"bad"
---@field value number The measured number itself.
---@field unit "percent"|"count"
---@field detail string The number rendered for display, e.g. "62.5% — 45 of 72".
---@field headline string The sentence. Phrased for the polarity it landed on.
---@field basis string What the number actually measured, including its blind spots. Required, not optional — see the module header for why.
---@field weight integer Ranking weight within a polarity.
---@field distance number How far past its own threshold the value sits; the tie-break under `weight`.
---@field tab string Page tab holding the rows behind this number.
---@field atool string? Analysis panel within `tab`, when the rows live in one.
---@field evidence string[]? Bounded list of `"<node id>#<fn>"` keys behind a negative verdict, in the same key scheme the page's compare marks use. Absent on a positive verdict and whenever the number has no per-function evidence.

---@class Documentation.Quicks.Result
---@field good Documentation.Quick[] Capped at `limit_good`, best first.
---@field bad Documentation.Quick[] Capped at `limit_bad`, worst first.
---@field total_good integer Before the cap.
---@field total_bad integer Before the cap.

---Tuning for `core/quicks.lua`.
---@class Documentation.Quicks.Opts
---@field thresholds? table<string, { good: number, bad: number }> Per-verdict cut points, merged over `quicks.DEFAULT_THRESHOLDS`. Keyed by the verdict `id` with hyphens written as underscores (`test_coverage`).
---@field limit_good? integer How many positive verdicts to keep. Default 5.
---@field limit_bad? integer How many negative verdicts to keep. Default 5.

--- One declared external tool, straight off `lib.nvim.deps.spec`'s own
--- `Lib.Deps.Tool` shape (`bin`/`why`/`pkg` required, `required`/`see`
--- optional) — not redefined here, since lib.nvim is already what parses it.
---@alias Documentation.Tools.Tool Lib.Deps.Tool

--- One malformed manifest entry — same shape as `Lib.Deps.Error`.
---@alias Documentation.Tools.Error Lib.Deps.Error

--- `ir.tools` — this repo's own `docs/install.json`/`docs/INSTALL.md`, as
--- declared, never as probed. See `core/tools.lua`.
---@class Documentation.Tools.Result
---@field source string Repo-relative path of the spec file that was read, e.g. "docs/install.json".
---@field tools Documentation.Tools.Tool[] Validated entries.
---@field errors Documentation.Tools.Error[] Malformed entries, never nil — a manifest can be partly valid.

---@class Documentation.IR
---@field meta Documentation.Meta
---@field quicks Documentation.Quicks.Result? Verdicts over this tree — see `quicks.lua`. Set by `scan_full`, so a bare `scan()` leaves it nil.
---@field root string Root node id.
---@field order string[] All node ids in deterministic walk order.
---@field nodes table<string, Documentation.Node>
---@field edges Documentation.Edge[] Type-reference edges from LuaLS enrichment. Always an array, empty when `opts.luals` did not run.
---@field duplicates Documentation.Duplicates.Result Functions grouped by structural shape — see `duplicates.lua`. Set by `scan_full`, so a bare `scan()` leaves it nil; serialised into the artifact because the grouping needs `fn.shape`, and a page reading the artifact has no parse tree to redo it with.
---@field docs Documentation.Docs.Result? Which prose file mentions which module or function — see `docs.lua`. Set by `scan_full`, so a bare `scan()` leaves it nil.
---@field tools Documentation.Tools.Result? This repo's declared `lib.nvim.deps` tools — see `core/tools.lua`. Set by `scan_full`; nil when lib.nvim.deps is unavailable or this repo ships no manifest.
---@field tag_links table<string, Documentation.TagLink> `requires_external` modules resolved through `opts.tag_files`. Always a table, empty when `opts.tag_files` is unset or nothing resolved — unlike `types_detail`, resolving is local and cheap, so there is no "did this run" question worth a nil.
---@field timing Documentation.Timing? Per-stage durations, set by `scan_full` when `opts.debug` is on. Deliberately **not** serialised into the artifact: a duration differs on every machine and `--check` byte-compares, so embedding one would make the map invalidate itself.

---A live handle returned by `docmap.install()`. Keeps a scanned IR in memory
---and, optionally, keeps it fresh — the object-in-source-code counterpart to
---the file-based `generate()`/`:DocMap` path.
---@class Documentation.Handle
---@field root string The root this handle was installed for; the registry key.
---@field ir fun(): Documentation.IR Current IR (already scanned; never triggers a scan itself).
---@field findings fun(): Documentation.Finding[] Current drift findings.
---@field node fun(id: string): Documentation.Node? Single node lookup on the current IR.
---@field requires fun(id: string): Documentation.Edge[] Require edges out of this node.
---@field required_by fun(id: string): Documentation.Edge[] Require edges into this node.
---@field callees fun(fn_key: string): Documentation.Edge[] Call edges out of a function, keyed `"<node id>#<declared name>"` — the same id scheme the HTML map uses.
---@field callers fun(fn_key: string): Documentation.Edge[] Call edges into a function, same key scheme.
---@field rescan fun(opts?: { luals?: boolean }): Documentation.IR, Documentation.Finding[] Force a rescan now; notifies `on_change` subscribers same as a watch-triggered one.
---@field on_change fun(cb: fun(ir: Documentation.IR, findings: Documentation.Finding[])): fun() Subscribe; returns an unsubscribe function.
---@field uninstall fun() Equivalent to `docmap.uninstall(handle)`.

---@class Documentation
---@field scan fun(opts: Documentation.Opts): Documentation.IR
---@field check fun(ir: Documentation.IR, opts: Documentation.Opts): Documentation.Finding[]
---@field scan_full fun(opts: Documentation.Opts): Documentation.IR, Documentation.Finding[] `scan` + optional LuaLS merge (`opts.luals`) + `check`, in one call. What `generate()` and `install()` both build on.
---@field generate fun(opts: Documentation.Opts): Documentation.IR, Documentation.Finding[], string[]
---@field install fun(opts: Documentation.Opts): Documentation.Handle
---@field uninstall fun(handle: Documentation.Handle|string): boolean Accepts a handle or a root path.
---@field render table

return {}
